name: Assign PR
on: 
  pull_request_target: 
    types: [opened, reopened, ready_for_review]

jobs:
  add-assignees:
    name: Assign
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.0
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
